
import { writable } from 'svelte/store';

// navigation fetch vars

const loading =     writable(false);
const navigate =  writable(true);
const directory =   writable("/");

export { loading, navigate, directory };

let directoryString; // god i hate this
    directory.subscribe((val) => { directoryString = val });
let pageLoaded; // god i hate this
    navigate.subscribe((val) => { pageLoaded = val });

// navigation controller

import navigation from "$lib/controllers/navigationDirectories.js";

let urlStoreArr =   writable([""]); // handles the transition direction
let directionX =    writable(0); // handles the transition direction
let directionY =    writable(0); // handles the transition direction

const directionProcessing = async (p,c,b = null) => {
    // calculates which direction it should move horizontally
    let xOffset = 0; // debugging purposes
    let pfr = p.split("/"); // "" is a fallback to prevent empty strings generated by
    let cfr = c.split("/"); // the router controller. Don't ask.

    if (cfr.length ^ pfr.length) { //checks if arrays are different in length
        if (pfr.length > cfr.length) {
            xOffset = 1;} //   forwards
        else {
            xOffset = -1;}} // backwards

    // calculates which direction it should move vertically
    let yOffset = 0; // debugging purposes
    let pyo = navigation.findIndex(e => e.path === "/" + cfr[1]);
    let cyo = navigation.findIndex(e => e.path === "/" + pfr[1]);

    if (!(xOffset ^ 0) && (pyo ^ cyo)) { // only moves if x isn't
        if (pyo > cyo) {
            yOffset = 1;}   // upwards
        else {
            yOffset = -1;}} // downwards

    // sets writable memory for fetching.
    directionY.set(yOffset);
    directionX.set(xOffset);

    // updates local url management.
    urlStoreArr.set(cfr);

    if (!b) {
        directory.set(c);
    } else {
        directory.set(b);
    }
}

export { urlStoreArr, directionX, directionY}

// overall URL handler

import { goto } from '$app/navigation';

const urlChanger = async (url) => {
    event.preventDefault(); // for some reason it breaks without this specifically on navigation buttons
        // Just leave it, I promise it's for the greater good.

    // url handling
    if(directoryString !== url && !pageLoaded) {
        loading.set(true);  //sets loading to default value
        await directionProcessing(directoryString, url); //updates router
        await fetch(directoryString)
            .then(async (e) => {
                goto(e.url);
            });
    }
};

export { urlChanger, directionProcessing};
